Add meta parameter
brooklyn-data/dbt_artifacts pull request #233
Opened 2022-10-27 21:18 UTC by robertholmes3

Adding meta columns for sources and exposures. 

[dbt docs - meta](https://docs.getdbt.com/reference/resource-configs/meta)

2022-10-28 08:38 UTC, NiallRees commented on models/sources/sources.sql
> +        cast(null as {{ type_array() }}) as meta
```suggestion
```

2022-10-28 08:39 UTC, NiallRees commented on models/sources/sources.sql
> +        cast(null as {{ type_json() }}) as meta
```suggestion
```
Please could you move `source_meta` and `meta` below the `endif`? They are always json types.

2022-10-28 08:41 UTC, NiallRees commented on macros/upload_sources.sql
> +                    parse_json('{{ tojson(source.meta) | replace("'","\\'") }}')  {# meta #}
Please can you add examples of these configs to the sources.yml for the integration tests? https://github.com/brooklyn-data/dbt_artifacts/blob/main/integration_test_project/models/sources.yml

2022-10-28 08:57 UTC, NiallRees commented on macros/upload_exposures.sql
> +                    '{{ tojson(exposure.owner) | replace("'","\\'") }}', {# owner #}
What's the thinking behind removing `parse_json`?

2022-10-28 08:58 UTC, NiallRees commented on macros/upload_exposures.sql
> +                    '{{ tojson(exposure.owner) | replace("'","\\'") }}', {# owner #}
This results in the following error:
```
Database Error
  Value has type STRING which cannot be inserted into column owner, which has type JSON at [15:21]
```

2022-10-28 09:05 UTC, NiallRees commented on macros/upload_exposures.sql
> +                    '{{ tojson(exposure.meta) | replace("'","\\'") }}' {# meta #}
```suggestion
                    parse_json('{{ tojson(exposure.meta) | replace("'","\\'") }}') {# meta #}
```

As this is a key: value object, I think it needs `parse_json`

2022-10-28 09:06 UTC, NiallRees commented
Thank you for this @robertholmes3! I've left a few comments but it's 90% there.

2022-11-02 17:55 UTC, robertholmes3 commented
@NiallRees thanks for the feedback! I made all of the suggested changes. I *Think* I may have brought in some other commit (whoops). Let me know if I need to make any other changes here :)

2023-03-04 18:46 UTC, k-lawecki commented
@NiallRees is there anything that should be fixed here that stops this from being merged?
We would love to use meta in exposures :)

2023-03-04 19:55 UTC, NiallRees commented
> @NiallRees is there anything that should be fixed here that stops this from being merged? We would love to use meta in exposures :)

Hi @k-lawecki, I'm no longer a member of the Brooklyn Data team but I'm sure someone will be able to help! cc @jecolvin

2023-03-06 14:24 UTC, jecolvin approved these changes

2023-03-10 07:07 UTC, k-lawecki commented
@jecolvin are there any plans for release that could include this one? :) We are trying to build an automated exposures catalogue and this would be a massive help

2023-03-31 08:55 UTC, glsdown requested changes
Hi @robertholmes3 . Sorry that this is so delayed, but we are putting in some time to work through all the open PRs and Issues now. I took a look at this one to get it merged, but was receiving this error:

```
Database Error
  002023 (22000): SQL compilation error:
  Expression type does not match column data type, expecting ARRAY but got VARCHAR(39) for column FRESHNESS
```

This is because when adding columns to the `upload_*` macros, and corresponding `sources` table, they need to be included at the end of the table to avoid clashes with data types and naming. I noticed that `source_description` was added in the middle which seems to have been the cause for it.

Due to the delays getting back to you, I've added comments where the changes would need to be made - only the `macros/upload_sources.sql` and `models/sources/sources.sql` files are affected by this. Please do check these though as it's harder to make the changes in comments than the files themselves.

Sorry again for the delay here.

2023-03-31 08:55 UTC, glsdown commented on models/sources/sources.sql
> +    cast(null as {{ type_string() }}) as source_description,
```suggestion
```

2023-03-31 08:55 UTC, glsdown commented on models/sources/sources.sql
> +        cast(null as {{ type_json() }}) as meta
```suggestion
    cast(null as {{ type_string() }}) as source_description,
    cast(null as {{ type_json() }}) as source_meta,
    cast(null as {{ type_json() }}) as meta
```

2023-03-31 08:55 UTC, glsdown commented on macros/upload_sources.sql
> +                '{{ source.source_description | replace("'","\\'") }}', {# source_description #}
```suggestion
```

2023-03-31 08:55 UTC, glsdown commented on macros/upload_sources.sql
> +                '{{ tojson(source.meta) | replace("'","\\'") }}' {# meta #}
```suggestion
                '{{ source.source_description | replace("'","\\'") }}', {# source_description #}
                '{{ tojson(source.source_meta) | replace("'","\\'") }}', {# source_meta #}
                '{{ tojson(source.meta) | replace("'","\\'") }}' {# meta #}
```

2023-03-31 08:55 UTC, glsdown commented on macros/upload_sources.sql
> +            {{ adapter.dispatch('parse_json', 'dbt_artifacts')(adapter.dispatch('column_identifier', 'dbt_artifacts')(12)) }},
```suggestion
            {{ adapter.dispatch('parse_json', 'dbt_artifacts')(adapter.dispatch('column_identifier', 'dbt_artifacts')(11)) }},
            {{ adapter.dispatch('column_identifier', 'dbt_artifacts')(12) }},
```

2023-03-31 08:55 UTC, glsdown commented on macros/upload_sources.sql
> +                    '{{ source.source_description }}', {# source_description #}
```suggestion
```

2023-03-31 08:55 UTC, glsdown commented on macros/upload_sources.sql
> +                    parse_json('{{ tojson(source.source_meta) | replace("'","\\'") }}'),  {# source_meta #}
```suggestion
                    '{{ source.source_description }}', {# source_description #}
                    parse_json('{{ tojson(source.source_meta) | replace("'","\\'") }}'),  {# source_meta #}
```

2024-08-07 10:09 UTC, closed without merging