Upload large number of tests (>20K) in chunks to prevent Snowflake errors
brooklyn-data/dbt_artifacts pull request #302
Opened 2023-05-02 20:51 UTC by nhrebinka

## Overview

This fixes the problem of uploading a large number of tests into Snowflake. [This issue](https://github.com/brooklyn-data/dbt_artifacts/issues/255) describes the problem in more details.

This version of code has been tested locally for 4+ months as we could not use `dbt_artifacts`'s original version which was breaking prod jobs.

## Update type - breaking / non-breaking

- [x] Minor bug fix
- [ ] Documentation improvements
- [ ] Quality of Life improvements
- [ ] New features (non-breaking change)
- [ ] New features (breaking change)
- [ ] Other (non-breaking change)
- [ ] Other (breaking change)

## What does this solve?

https://github.com/brooklyn-data/dbt_artifacts/issues/255

## Outstanding questions

## What databases have you tested with?

- [x] Snowflake
- [ ] Google BigQuery
- [ ] Databricks
- [ ] Spark
- [ ] N/A

2023-05-05 12:11 UTC, glsdown requested changes
Thank you so much for putting the effort into building this, and creating a great addition.

I've left some comments around suggested improvements for efficiency, as well as to fix the failing CI checks. Let me know if you have any questions.

P.S. apologies for the weird commit and revert at the end - I was on the wrong branch when I pushed 🤦

2023-05-05 12:11 UTC, glsdown commented on macros/upload_results.sql
> +            {% set content_tests = upload_tests(tests_set, i+1, upload_limit) %}
I believe this is why the integration tests are currently failing:

```suggestion
            {% set content_tests = dbt_artifacts.upload_tests(tests_set, i+1, upload_limit) %}
```

2023-05-05 12:11 UTC, glsdown commented on macros/upload_results.sql
> +        {% set upload_limit = 5000 %}
This looks like it would also be a great solution for #232 although BigQuery typically has a lower limit. So I wonder if it would be good to include something like this here:

```suggestion
        {% set upload_limit = 750 if target.type == 'bigquery' else 5000 %}
```

2023-05-05 12:11 UTC, glsdown commented on macros/upload_results.sql
> +        {% for i in range(n) -%}
Rather than complicate the `upload_tests` macros by passing in the additional parameters, it might be worth instead only passing in the slice of the tests list that we want to use:

```sql
        {%- for i in range(0, tests_set | length, upload_limit) -%}
            {% set content_tests = dbt_artifacts.upload_tests(tests_set[i: i + upload_limit]) %}
            {{ dbt_artifacts.insert_into_metadata_table(
                database_name=tests.database,
                schema_name=tests.schema,
                table_name=tests.identifier,
                content=content_tests
                )
            }}
        {% endfor -%}
```

This means that the logic in the individual `default__get_tests_dml_sql` and `bigquery__get_tests_dml_sql` shouldn't need to change. It will also mean that those macros don't have to loop through the entire list of tests on each run, so should speed things up.

2023-05-05 16:08 UTC, nhrebinka commented on macros/upload_results.sql
> +        {% for i in range(n) -%}
thanks @glsdown, excellent suggestion!

2023-05-05 16:20 UTC, nhrebinka commented
@glsdown it is ready for integration testing. I ran some basic testing locally, looks good and uploads the right # of tests.

2023-05-12 11:35 UTC, glsdown approved these changes
This looks great, and is a really useful enhancement - thank you for taking the time to do it.

2023-05-12 11:36 UTC, merged