add else clause to for if loops
brooklyn-data/dbt_artifacts pull request #386
Opened 2023-09-21 01:53 UTC by kenpokiwi

2023-09-21 09:01 UTC, glsdown commented on macros/upload_individual_datasets/upload_model_executions.sql
>                      {% endfor %}
I think originally this `loop.length` section was designed for the use-case you are fixing here, but doesn't make sense (it wouldn't run if the loop was empty). That means it can be removed I believe. Looking at the logic here, it also looks like it could be hugely simplified using Jinja filtering:

```
                {% set compile_started_at = (model.timing | selectattr("name", "eq", "compile") | first | default({})).get("started_at") %}
                {% if compile_started_at %}'{{ compile_started_at }}'{% else %}null{% endif %}, {# compile_started_at #}
                {% set query_completed_at = (model.timing | selectattr("name", "eq", "execute") | first | default({})).get("completed_at") %}
                {% if query_completed_at %}'{{ query_completed_at }}'{% else %}null{% endif %}, {# query_completed_at #}
```

I think this would aid readability and consistency. What do you think?

2023-09-21 20:00 UTC, kenpokiwi commented on macros/upload_individual_datasets/upload_model_executions.sql
>                      {% endfor %}
Yes I think that is much more elegant :)

2023-09-25 14:17 UTC, glsdown commented on macros/upload_individual_datasets/upload_model_executions.sql
>                      {% endfor %}
Thanks for looking at this. For consistency, please could you also add the same logic into the other two macros in here for BQ and Snowflalke? From lines 88 and 164. Thanks!

2023-09-26 19:06 UTC, kenpokiwi commented on macros/upload_individual_datasets/upload_model_executions.sql
>                      {% endfor %}
Thanks for the feedback. Update done.

2023-09-28 10:16 UTC, glsdown approved these changes

2023-09-28 10:21 UTC, glsdown requested changes

2023-09-28 10:21 UTC, glsdown commented on macros/upload_individual_datasets/upload_model_executions.sql
>                  {% endfor %}
```suggestion
```

2023-09-28 13:25 UTC, glsdown approved these changes

2023-09-28 13:27 UTC, glsdown commented
Thanks for all your work on this!

2023-09-28 13:27 UTC, merged