Format all models for consistency
brooklyn-data/dbt_artifacts pull request #390
Opened 2023-10-02 18:09 UTC by poloaraujo

## Overview

Currently there are inconsistencies in the SQL scripts styles used (e.g. trailing vs leading commas). I've formatted al sources, staging models, fact models and core models (both dimensional and fact) to have a consistent format for both spacing and commas (of which all use trailing)

## Update type - breaking / non-breaking

- [ ] Minor bug fix
- [ ] Documentation improvements
- [ ] Quality of Life improvements
- [ ] New features (non-breaking change)
- [ ] New features (breaking change)
- [x] Other (non-breaking change)
- [ ] Other (breaking change)
- [ ] Release preparation

## What does this solve?

Issue #383 

## Outstanding questions

So far, I've only tested locally with Snowflake

## What databases have you tested with?

- [x] Snowflake
- [ ] Google BigQuery
- [ ] Databricks
- [ ] Spark
- [ ] N/A

2023-10-02 18:20 UTC, glsdown approved these changes
Pending approval from our robot overlords (i.e. the CI Linter) this looks great to me! Thank you for doing this. 🎉

2024-08-22 16:12 UTC, llifoawing requested changes
Hey @poloaraujo - resurrecting this PR so we can merge your changes!
- SQLfluff failed due to 3 single select targets being on new lines.
- I was running into errors when running tox locally related to this [issue](https://github.com/sqlfluff/sqlfluff/issues/5841#issuecomment-2135297644) - can you upgrade sqlfluff-templater-dbt~=3.0.7

2024-08-22 16:12 UTC, llifoawing commented on models/dim_dbt__current_models.sql
> +            *
SQLFluff raised LT09 - single select target doesnt need to be on new line

2024-08-22 16:12 UTC, llifoawing commented on models/dim_dbt__current_models.sql
> +            *
SQLFluff raised LT09 - single select target doesnt need to be on new line

2024-08-22 16:12 UTC, llifoawing commented on models/dim_dbt__current_models.sql
> +            *
SQLFluff raised LT09 - single select target doesnt need to be on new line

2024-08-30 18:34 UTC, llifoawing approved these changes

2024-08-30 18:35 UTC, merged