Add Trino integration, tests and configurations
brooklyn-data/dbt_artifacts pull request #413
Opened 2023-12-18 20:09 UTC by EminUZUN

## Overview

## Update type - breaking / non-breaking

- [ ] Minor bug fix
- [ ] Documentation improvements
- [ ] Quality of Life improvements
- [ X] New features (non-breaking change)
- [ ] New features (breaking change)
- [ ] Other (non-breaking change)
- [ ] Other (breaking change)
- [ ] Release preparation

## What does this solve?

It adds support for trino

## Outstanding questions

## What databases have you tested with?

- [ ] Snowflake
- [ ] Google BigQuery
- [ ] Databricks
- [ ] Spark
- [ ] N/A
- [x] Trino

2023-12-19 14:34 UTC, EminUZUN commented
I have run main branch test package: https://github.com/EminUZUN/dbt_artifacts/actions/runs/7263229785/job/19788068739
It run for 1_5_0 and above

2024-01-12 20:24 UTC, EminUZUN commented
Hey @glsdown, is this project alive? Or will it be retired?

2024-04-18 18:16 UTC, danielyahn commented
@EminUZUN @glsdown any chance this can be merged?

2024-08-08 13:31 UTC, DenGodunov reviewed
All done correctly

2024-08-08 13:32 UTC, DenGodunov approved these changes

2024-08-08 13:33 UTC, DenGodunov commented
@glsdown please review changes?

2024-10-29 13:53 UTC, netanelm-upstream commented
@glsdown Any update on that?

2025-01-15 05:48 UTC, krutoileshii commented
Any news on this?

2025-02-14 20:31 UTC, dlawin commented on macros/upload_individual_datasets/upload_test_executions.sql
> +                {% if test.adapter_response.rows_affected is none %}
I had to alter this line to
```suggestion
                {% if test.adapter_response.rows_affected is none or test.adapter_response is not defined %}
```

to avoid an empty string

2025-02-14 20:51 UTC, dlawin commented on macros/upload_individual_datasets/upload_model_executions.sql
> +                {% if model.adapter_response.rows_affected is none %}
same issue https://github.com/brooklyn-data/dbt_artifacts/pull/413/files#r1956687209

2025-03-12 04:28 UTC, krutoileshii commented on macros/upload_individual_datasets/upload_model_executions.sql
> +                {% if model.adapter_response.rows_affected is none %}
What's needed to get this to a mergable state?

2025-05-02 15:14 UTC, krutoileshii commented
Can someone tell me what needs to be updated here to get it merged and i will do it.

2025-05-02 18:43 UTC, EminUZUN commented
@mtcarlone is there anything which I can do so this can be merged?

2025-05-02 20:00 UTC, mtcarlone commented
@EminUZUN can we resolve the conflicts on this PR. There are a good amount of them

Thanks

2025-05-02 20:38 UTC, krutoileshii commented
I'm looking at the upload Tests, and quoting seems odd, Editor complains on my end but not sure. 

`'{{ tojson(test) | replace("'", "''") }}' {# all_results #}`
i think it should be
` '{{ tojson(test) | replace("'", "'''") }}' {# all_results #}`

2025-05-02 20:48 UTC, EminUZUN commented
@mtcarlone i have fixed conflicts. 
@krutoileshii I guess you were trying to do same time.

2025-05-02 20:50 UTC, mtcarlone commented
Thanks @EminUZUN I'll take a look

2025-05-02 21:01 UTC, EminUZUN commented
@mtcarlone  there was suggestion about {% if test.adapter_response.rows_affected is none or test.adapter_response.rows_affected is not defined %} this from @dlawin  I have updated those also.

2025-05-02 21:02 UTC, krutoileshii commented
> @mtcarlone i have fixed conflicts. @krutoileshii I guess you were trying to do same time.

was trying to help :) since this been stuck for a while. 

Thank You both.

2025-05-06 19:30 UTC, EminUZUN commented
@mtcarlone is there any problem with pr?

2025-05-06 20:08 UTC, mtcarlone requested changes
One comment can be disregarded, but would appreciate if we can resolve some whitespace changes in these macros. Otherwise, once that's resolved we should be good

2025-05-06 20:08 UTC, mtcarlone commented on macros/upload_individual_datasets/upload_models.sql
> +                        '{{ tojson(model) | replace("'", "''") }}' {# all_results #}
**No Action Needed**
`microbatch` is not supported at this time for `dbt-trino`. However, this won't serialize if/when `microbatch` becomes supported. Not an issue at this moment, but leaving this comment in case we want to handle this now

2025-05-06 20:08 UTC, mtcarlone commented on macros/upload_individual_datasets/upload_snapshot_executions.sql
> +                    (
Can we revert the whitespace here and in lines 36:38, 40, and 47? The proposed whitespace/indentation makes this harder to read now

2025-05-06 20:08 UTC, mtcarlone commented
@EminUZUN left one small comment. If that can be resolved this is good on my end

2025-05-07 17:10 UTC, EminUZUN commented
@

> @EminUZUN left one small comment. If that can be resolved this is good on my end

I have fixed whitespace problems. And opened issue about micro batch.

2025-05-07 21:15 UTC, mtcarlone approved these changes

2025-05-09 13:14 UTC, merged