Adds the current models model with recent run stats
brooklyn-data/dbt_artifacts pull request #79
Opened 2022-02-01 10:51 UTC by alanmcruickshank

This resolves #76, by instead bringing in a new model rather than replacing the old one for backward compatibility. Practically it probably should replace most usages of the existing model but that's a job for people using the package.

2022-02-01 10:58 UTC, alanmcruickshank commented
@NiallRees - do you think that this PR should also remove/replace the existing `fct_dbt__latest_full_model_executions`? I was hesitant to just totally rip it out because of the the dependency through to `fct_dbt__critical_path` - but I'm not sure how the concept of the critical path maps to our current use case.

2022-02-02 08:34 UTC, NiallRees commented on models/schemas.yml
> +      represents the models which are current live in the dbt project.
```suggestion
      represents the models which are currently live in the dbt project.
```

2022-02-02 08:34 UTC, NiallRees requested changes
Happy with all this @alanmcruickshank, please can you update the README.md with the new model?

2022-02-02 13:28 UTC, NiallRees approved these changes

2022-02-02 13:28 UTC, merged